#!/usr/bin/env bash

set -eu

VERSION=5.2.2

docker pull docker.io/debian:9.3-slim
docker build -t docker.io/copla/physiological-networks-tds:${VERSION} .
docker run docker.io/copla/physiological-networks-tds:${VERSION} ccagent --version
docker push docker.io/copla/physiological-networks-tds:${VERSION}
